Repository uniiverse/milkyway, pull requests merged in 2022-11, with the labels that each got.

#106 Downgrade babel requirement
  index.js
  package-lock.json
  package.json
Labels: size/XXL

#107 bumping version number
  package.json
Labels: size/XS

#108 Revert "Downgrade babel requirement"
  index.js
  package-lock.json
  package.json
Labels: size/XXL

#109 bump version 0.2.18
  package.json
Labels: size/XS

#110 Promotional Pill
  components/Pill/Pill.jsx
  components/Pill/Pill.less
  components/Pill/index.js
  stories/index.stories.js
  stories/pill/index.js
  webpack.index.js
Labels: size/L
